apiVersion: v1
kind: Secret
metadata:
  name: virtual-assistant-secret
type: Opaque
data:
  virt-ass-connection: "SG9zdD1wb3N0Z3JlLXJlbGVhc2UtcG9zdGdyZXNxbDtQb3J0PTU0MzI7RGF0YWJhc2U9dmlydHVhbF9hc3Npc3RhbnQ7VXNlcm5hbWU9dmlydHVhbF9hc3Npc3RhbnQ7UGFzc3dvcmQ9dmlydF9hc3M7" 

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: virtual-assistant-cm
data:
  port: "8000"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtual-assistant-dp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: virtual-assistant-app
  template:
    metadata:
      labels:
        app: virtual-assistant-app
    spec:
      containers:
        - name: virtual-assistant
          image: cl6wn/virtual_assistant:v2.1.7
          env:
            - name: HostOptions__Port
              valueFrom:
                configMapKeyRef:
                  name: virtual-assistant-cm
                  key: port
            - name: ConnectionStrings__VirtAssDb
              valueFrom:
                secretKeyRef:
                  name: virtual-assistant-secret
                  key: virt-ass-connection
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8000
            - containerPort: 8001

---
apiVersion: v1
kind: Service
metadata:
  name: virtual-assistant-svc
  labels:
    app: virtual-assistant
spec:
  selector:
    app: virtual-assistant-app
  ports:
    - name: main
      port: 8000
    - name: metrics
      port: 8001

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: virtual-assistant-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /otusapp/eygerman/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: virtual-assistant-svc
                port:
                  number: 8000
          # для дебага, оценить метрики снаружи куба без форварда портов
          - path: /prometheus/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: virtual-assistant-svc
                port:
                  number: 8001

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: virtual-assistant-monitor
  labels:
    app: virtual-assistant-monitor  
spec:
  endpoints:
    - port: metrics
      scrapeTimeout: 30s
      path: /metrics
      honorLabels: true
      scheme: http
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: virtual-assistant